use database health_db;
create schema gold;
use schema gold;

--CREATING TABLE GOLD_CLAIMS_SUMMARY
CREATE OR REPLACE TABLE GOLD_CLAIMS_SUMMARY AS
SELECT
    dat.YEAR,
    dat.MONTH,
    dat.QUARTER,
    dat.MONTH_NAME,

    fc.CLAIM_DECISION,

    dp.GENDER,
    dp.AGE_BAND,
    dp.INSURANCE_TIER,

    df.STATE_CODE,
    df.TYPE_OF_CONTROL,

    dd.SEVERITY_TIER,
    dd.CHAPTER,

    COUNT(*) AS TOTAL_CLAIMS,
    COUNT(DISTINCT fc.PATIENT_SK) AS UNIQUE_PATIENTS,

    SUM(fc.BILLED_AMOUNT) AS TOTAL_BILLED,
    SUM(fc.PAID_AMOUNT) AS TOTAL_PAID,

    ROUND(
        COUNT_IF(fc.CLAIM_DECISION = 'DENIED') * 100.0 / NULLIF(COUNT(*),0),
        2
    ) AS DENIAL_RATE_PCT,

    ROUND(
        SUM(fc.PAID_AMOUNT) * 100.0 / NULLIF(SUM(fc.BILLED_AMOUNT),0),
        2
    ) AS COLLECTION_RATE_PCT

FROM SILVER.FACT_CLAIMS fc

LEFT JOIN SILVER.PATIENT_DIM dp
    ON fc.PATIENT_SK = dp.PATIENT_SK
   AND dp.IS_CURRENT = TRUE

LEFT JOIN SILVER.FACILITY_DIM df
    ON fc.FACILITY_SK = df.FACILITY_SK
   AND df.IS_CURRENT = TRUE

LEFT JOIN SILVER.DIAGNOSIS_DIM dd
    ON fc.DIAG_SK = dd.DIAG_SK

LEFT JOIN SILVER.DATE_DIM dat
    ON fc.DATE_SK = dat.DATE_SK

GROUP BY
    dat.YEAR, dat.MONTH, dat.QUARTER, dat.MONTH_NAME,
    fc.CLAIM_DECISION,
    dp.GENDER, dp.AGE_BAND, dp.INSURANCE_TIER,
    df.STATE_CODE, df.TYPE_OF_CONTROL,
    dd.SEVERITY_TIER, dd.CHAPTER;



--creating 2 nd table GOLD_DRUG_ANALYTICS
CREATE OR REPLACE TABLE GOLD_DRUG_ANALYTICS AS
SELECT
    d.Brnd_Name AS BRAND_NAME,
    d.Gnrc_Name AS GENERIC_NAME,

    p.PRSCRBR_TYPE AS SPECIALTY,
    p.PRSCRBR_STATE AS STATE,

    CASE
        WHEN d.Brnd_Name = d.Gnrc_Name THEN 'GENERIC'
        ELSE 'BRANDED'
    END AS DRUG_TYPE,

    SUM(TRY_TO_NUMBER(d.Tot_Clms)) AS TOTAL_CLAIMS,
    SUM(TRY_TO_NUMBER(d.Tot_Drug_Cst)) AS TOTAL_COST,
    SUM(TRY_TO_NUMBER(d.Tot_Benes)) AS TOTAL_BENES

FROM health_db_BRONZE.DRUG_DATA d

LEFT JOIN SILVER.PHYSICIAN_DIM p
    ON d.Prscrbr_NPI = p.NPI
   AND p.IS_CURRENT = TRUE

GROUP BY
    d.Brnd_Name, d.Gnrc_Name,
    p.PRSCRBR_TYPE, p.PRSCRBR_STATE;





    --- CREATING 3rd TABLE GOLD_CAPACITY_KPI

CREATE OR REPLACE TABLE GOLD_CAPACITY_KPI AS
SELECT
    f.PROVIDER_CCN,
    f.FACILITY_NAME,
    f.STATE_CODE,
    f.TYPE_OF_CONTROL,

    TRY_TO_NUMBER(h.number_of_beds) AS LICENSED_BEDS,

    dat.YEAR AS FISCAL_YEAR,

    TRY_TO_NUMBER(fc.STAFFED_BEDS) AS STAFFED_BEDS,
    TRY_TO_NUMBER(fc.OCCUPIED_BEDS) AS OCCUPIED_BEDS,
    fc.OCCUPANCY_PCT,

    ROUND(
        fc.OCCUPANCY_PCT,
        2
    ) AS OCCUPANCY_PCT_ROUNDED,

    CASE
        WHEN fc.OCCUPANCY_PCT >= 85 THEN 'OVER CAPACITY'
        WHEN fc.OCCUPANCY_PCT >= 70 THEN 'OPTIMAL'
        WHEN fc.OCCUPANCY_PCT >= 50 THEN 'UNDER UTILIZED'
        ELSE 'CRITICAL'
    END AS CAPACITY_TIER

FROM SILVER.FACT_CAPACITY fc

LEFT JOIN SILVER.FACILITY_DIM f
    ON fc.FACILITY_SK = f.FACILITY_SK
   AND f.IS_CURRENT = TRUE

LEFT JOIN health_db_BRONZE.HOSPITAL_COST h
    ON f.PROVIDER_CCN = h.provider_ccn

LEFT JOIN SILVER.DATE_DIM dat
    ON fc.DATE_SK = dat.DATE_SK;
    select * from GOLD_CAPACITY_KPI;


-- CREATING 4 th TABLE MONTHLY TREND VIEW
CREATE OR REPLACE VIEW MV_CLAIMS_BY_MONTH AS
SELECT
    YEAR,
    MONTH,
    MONTH_NAME,
    COUNT(*) AS TOTAL_CLAIMS,
    SUM(TOTAL_BILLED) AS TOTAL_BILLED,
    SUM(TOTAL_PAID) AS TOTAL_PAID
FROM GOLD_CLAIMS_SUMMARY
GROUP BY YEAR, MONTH, MONTH_NAME;



--4 th table 
CREATE OR REPLACE TABLE GOLD_PATIENT_SUMMARY AS
SELECT
    dp.PATIENT_SK,
    dp.PATIENT_ID,
    dp.GENDER,
    dp.BIRTH_DATE,
    dp.AGE_BAND,
    dp.INSURANCE_TIER,

    COUNT(fc.CLAIM_SK) AS TOTAL_CLAIMS,
    SUM(fc.BILLED_AMOUNT) AS TOTAL_BILLED,
    SUM(fc.PAID_AMOUNT) AS TOTAL_PAID,

    COUNT_IF(fc.CLAIM_DECISION = 'DENIED') AS TOTAL_DENIED

FROM SILVER.PATIENT_DIM dp
LEFT JOIN SILVER.FACT_CLAIMS fc
    ON dp.PATIENT_SK = fc.PATIENT_SK
WHERE dp.IS_CURRENT = TRUE
GROUP BY
    dp.PATIENT_SK, dp.PATIENT_ID,
    dp.GENDER, dp.BIRTH_DATE,
    dp.AGE_BAND, dp.INSURANCE_TIER;

show tables;


SHOW VIEWS IN SCHEMA GOLD;
--  VERIFICATION
-- ============================================================



--2 nd testing 
SELECT 'GOLD_CLAIMS_SUMMARY' AS obj, COUNT(*) FROM GOLD.GOLD_CLAIMS_SUMMARY
UNION ALL
SELECT 'GOLD_DRUG_ANALYTICS', COUNT(*) FROM GOLD.GOLD_DRUG_ANALYTICS
UNION ALL
SELECT 'GOLD_CAPACITY_KPI', COUNT(*) FROM GOLD.GOLD_CAPACITY_KPI
UNION ALL
SELECT 'GOLD_PATIENT_SUMMARY', COUNT(*) FROM GOLD.GOLD_PATIENT_SUMMARY
UNION ALL
SELECT 'MV_CLAIMS_BY_MONTH', COUNT(*) FROM GOLD.MV_CLAIMS_BY_MONTH;
SHOW TABLES IN SCHEMA HEALTH_DB.GOLD;


select * from MV_CLAIMS_BY_MONTH; 
SELECT AGE_BAND, COUNT(*) AS rowss, SUM(TOTAL_BILLED) AS billed
FROM GOLD.GOLD_CLAIMS_SUMMARY
GROUP BY AGE_BAND;

SELECT COUNT(*) AS total_fact_rows,
       COUNT(DISTINCT fc.PATIENT_SK) AS distinct_sk_in_fact
FROM SILVER.FACT_CLAIMS fc;

SELECT COUNT(*) AS total_dim_rows,
       COUNT(DISTINCT PATIENT_SK) AS distinct_sk_in_dim
FROM SILVER.PATIENT_DIM
WHERE IS_CURRENT = TRUE;

SELECT DATA_TYPE, COLUMN_NAME, TABLE_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'PATIENT_SK'
AND TABLE_NAME IN ('FACT_CLAIMS', 'PATIENT_DIM');

SELECT COUNT(*) AS matching_rows
FROM SILVER.PATIENT_DIM dp
JOIN SILVER.FACT_CLAIMS fc
    ON dp.PATIENT_SK = fc.PATIENT_SK;

SELECT COUNT(*) AS null_age_band_in_dim
FROM SILVER.PATIENT_DIM
WHERE IS_CURRENT = TRUE AND AGE_BAND IS NULL;

SELECT COUNT(*) AS rows_with_agebandnull_but_matched
FROM SILVER.FACT_CLAIMS fc
JOIN SILVER.PATIENT_DIM dp
    ON fc.PATIENT_SK = dp.PATIENT_SK
   AND dp.IS_CURRENT = TRUE
WHERE dp.AGE_BAND IS NULL;

CREATE OR REPLACE TABLE GOLD_CLAIMS_SUMMARY AS
SELECT
    dat.YEAR,
    dat.MONTH,
    dat.QUARTER,
    dat.MONTH_NAME,
    fc.CLAIM_DECISION,
    dp.GENDER,
    dp.AGE_BAND,
    dp.INSURANCE_TIER,
    df.STATE_CODE,
    df.TYPE_OF_CONTROL,
    dd.SEVERITY_TIER,
    dd.CHAPTER,
    COUNT(*) AS TOTAL_CLAIMS,
    COUNT(DISTINCT fc.PATIENT_SK) AS UNIQUE_PATIENTS,
    SUM(fc.BILLED_AMOUNT) AS TOTAL_BILLED,
    SUM(fc.PAID_AMOUNT) AS TOTAL_PAID,
    ROUND(COUNT_IF(fc.CLAIM_DECISION = 'DENIED') * 100.0 / NULLIF(COUNT(*),0), 2) AS DENIAL_RATE_PCT,
    ROUND(SUM(fc.PAID_AMOUNT) * 100.0 / NULLIF(SUM(fc.BILLED_AMOUNT),0), 2) AS COLLECTION_RATE_PCT
FROM SILVER.FACT_CLAIMS fc
LEFT JOIN SILVER.PATIENT_DIM dp ON fc.PATIENT_SK = dp.PATIENT_SK AND dp.IS_CURRENT = TRUE
LEFT JOIN SILVER.FACILITY_DIM df ON fc.FACILITY_SK = df.FACILITY_SK AND df.IS_CURRENT = TRUE
LEFT JOIN SILVER.DIAGNOSIS_DIM dd ON fc.DIAG_SK = dd.DIAG_SK
LEFT JOIN SILVER.DATE_DIM dat ON fc.DATE_SK = dat.DATE_SK
GROUP BY
    dat.YEAR, dat.MONTH, dat.QUARTER, dat.MONTH_NAME,
    fc.CLAIM_DECISION,
    dp.GENDER, dp.AGE_BAND, dp.INSURANCE_TIER,
    df.STATE_CODE, df.TYPE_OF_CONTROL,
    dd.SEVERITY_TIER, dd.CHAPTER;

    SELECT AGE_BAND, COUNT(*) AS rowss, SUM(TOTAL_BILLED) AS billed
FROM GOLD.GOLD_CLAIMS_SUMMARY
GROUP BY AGE_BAND;
SELECT DATA_TYPE, COLUMN_NAME, TABLE_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'FACILITY_SK'
AND TABLE_NAME IN ('FACT_CLAIMS', 'FACILITY_DIM');
SELECT COUNT(*) AS matching_rows
FROM SILVER.FACT_CLAIMS fc
JOIN SILVER.FACILITY_DIM df
    ON fc.FACILITY_SK = df.FACILITY_SK
   AND df.IS_CURRENT = TRUE;
   SELECT COUNT(*) AS total_facility_rows,
       COUNT_IF(IS_CURRENT = TRUE) AS current_true_count
FROM SILVER.FACILITY_DIM;
SELECT DATA_TYPE, COLUMN_NAME, TABLE_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'FACILITY_SK'
AND TABLE_NAME IN ('FACT_CLAIMS', 'FACILITY_DIM');

SELECT COUNT(*) AS matching_rows_no_current_filter
FROM SILVER.FACT_CLAIMS fc
JOIN SILVER.FACILITY_DIM df
    ON fc.FACILITY_SK = df.FACILITY_SK;

    SELECT MIN(FACILITY_SK) AS min_sk, MAX(FACILITY_SK) AS max_sk, COUNT(DISTINCT FACILITY_SK) AS distinct_sk
FROM SILVER.FACT_CLAIMS;
SELECT MIN(FACILITY_SK) AS min_sk, MAX(FACILITY_SK) AS max_sk, COUNT(DISTINCT FACILITY_SK) AS distinct_sk
FROM SILVER.FACILITY_DIM;
SELECT COUNT(*) AS after_join_rows
FROM health_db_BRONZE.DRUG_DATA d
LEFT JOIN SILVER.PHYSICIAN_DIM p
    ON d.Prscrbr_NPI = p.NPI
   AND p.IS_CURRENT = TRUE;
  SELECT COUNT(*) AS drug_data_rows
FROM health_db_BRONZE.DRUG_DATA; 
SELECT Tot_Drug_Cst, TRY_TO_NUMBER(Tot_Drug_Cst) AS parsed_value
FROM health_db_BRONZE.DRUG_DATA
ORDER BY TRY_TO_NUMBER(Tot_Drug_Cst) DESC
LIMIT 20;

SELECT Tot_Drug_Cst, Tot_Clms, Tot_Benes, Brnd_Name, Gnrc_Name, Prscrbr_NPI
FROM health_db_BRONZE.DRUG_DATA
WHERE TRY_TO_NUMBER(Tot_Drug_Cst) > 100000000
ORDER BY TRY_TO_NUMBER(Tot_Drug_Cst) DESC
LIMIT 10;

SELECT COUNT(*) AS extreme_rows
FROM health_db_BRONZE.DRUG_DATA
WHERE TRY_TO_NUMBER(Tot_Drug_Cst) > 10000000;

SELECT Tot_Drug_Cst, Tot_Clms,
       TRY_TO_NUMBER(Tot_Drug_Cst) / NULLIF(TRY_TO_NUMBER(Tot_Clms), 0) AS cost_per_claim
FROM health_db_BRONZE.DRUG_DATA
ORDER BY TRY_TO_NUMBER(Tot_Drug_Cst) DESC
LIMIT 10;
SELECT CLAIM_DECISION, COUNT(*) AS rowss, SUM(TOTAL_CLAIMS) AS claims
FROM GOLD.GOLD_CLAIMS_SUMMARY
GROUP BY CLAIM_DECISION;

SELECT MIN(DATE_SK) AS min_sk, MAX(DATE_SK) AS max_sk, COUNT(DISTINCT DATE_SK) AS distinct_sk
FROM SILVER.FACT_CAPACITY;

SELECT MIN(YEAR) AS min_year, MAX(YEAR) AS max_year, COUNT(DISTINCT YEAR) AS distinct_years
FROM SILVER.DATE_DIM;

SELECT SPECIALTY, SUM(TOTAL_BENES) AS benes, COUNT(*) AS rowss
FROM GOLD.GOLD_DRUG_ANALYTICS
GROUP BY SPECIALTY
ORDER BY benes DESC;
